### ISSUE TITLE
[babel-preset-razzle] TypeError: [BABEL] commonjsPlugin.apply is not a function

### ISSUE THREAD

**Issue by nnnoel** [jaredpalmer/razzle#1541]
## 🐛 Bug report

After integrating razzle to an existing project, when I go to run `razzle start`, I get the following error:

```
~/node_modules/babel-preset-razzle/babel-plugins/commonjs.js:4
  const commonjs = commonjsPlugin.apply(null, arguments);
                                  ^
Error: Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):
TypeError: [BABEL] ~/server/app.js: commonjsPlugin.apply is not a function (While processing: "programmatic item")
```

which works after I change this line to the following:
```
const commonjs = commonjsPlugin.default.apply(null, arguments);
```

I can't share any of the existing code, but I can share any relevant dependencies that could be related to this, such as babel plugins, etc.. FWIW, I'm also using the `newBabel` experimental flag, because the root of the project uses a `babel.config.js`, which seems to get ignored otherwise.

### Expected behavior

It shouldn't error

### Suggested solution(s)

I'm not exactly sure. This bug doesn't happen when using one of the example templates, so there might be an edge case with my project I'm missing.

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Razzle           | ^3.3.11, ^3.3.12
| Razzle Plugins   | none.
| Node             | v14.13.0
| Browser          |
| npm/Yarn         | yarn v1.22.10
| Operating System | macOS 10.15.7
| TypeScript       |
| React            | ^16.10.2

**Comment by fivethreeo** [comment]
Your code uses module.exports ?

**Comment by nnnoel** [comment]
All of the server app code and `*.config.js` files use commonjs, but the client app uses es6 syntax.

**Comment by fivethreeo** [comment]
Fixed in 
v3.3.12

**Comment by nnnoel** [comment]
> Fixed in
> v3.3.12

I upgraded to v3.3.12, but I still get this issue. :/

Installed node_modules from scratch, same thing.

**Comment by fivethreeo** [comment]
Can you post the error as is now?

**Comment by fivethreeo** [comment]
https://github.com/jaredpalmer/razzle/commit/aa76ad6c0bcd0c64901fd0b941cef6d2dab45d8c

**Comment by nnnoel** [comment]
It's the same exact error. After inspecting the node module itself, I see that that line is still
```js
const commonjs = commonjsPlugin.apply(null, arguments);
```
instead of the one shown in https://github.com/jaredpalmer/razzle/commit/aa76ad6c0bcd0c64901fd0b941cef6d2dab45d8c

**Comment by fivethreeo** [comment]
And the package json says 3.3.12?

**Comment by nnnoel** [comment]
> And the package json says 3.3.12?

Yep. `"razzle": "^3.3.12"`

**Comment by fivethreeo** [comment]
I mean, the one in the presets package json

**Comment by fivethreeo** [comment]
Ah you need the preset aswell. And in worst case if it does not work add babel-preset-razzle with a exact version in resolutions.

**Comment by nnnoel** [comment]
This is the package.json of the `babel-preset-razzle` that installed

```json
{
  "name": "babel-preset-razzle",
  "version": "3.3.11",
  "description": "Babel presets for Razzle",
  "main": "index.js",
  "author": "jaredpalmer",
  "repository": "git@github.com:jaredpalmer/razzle.git",
  "license": "MIT",
  "files": [
    "index.js",
    "razzle-four-preset.js",
    "babel-plugins/amp-attributes.js",
    "babel-plugins/commonjs.js",
    "babel-plugins/jsx-pragma.js",
    "babel-plugins/no-anonymous-default-export.js",
    "babel-plugins/optimize-hook-destructuring.js"
  ],
  "dependencies": {
    "@babel/core": "7.11.1",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-nullish-coalescing-operator": "7.10.4",
    "@babel/plugin-proposal-numeric-separator": "7.10.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.9.5",
    "@babel/plugin-proposal-optional-chaining": "7.11.0",
    "@babel/plugin-syntax-bigint": "7.8.3",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-modules-commonjs": "^7.9.0",
    "@babel/plugin-transform-react-jsx-source": "^7.9.0",
    "@babel/plugin-transform-runtime": "^7.9.0",
    "@babel/preset-env": "^7.9.5",
    "@babel/preset-react": "^7.9.4",
    "@babel/preset-typescript": "^7.9.0",
    "@babel/runtime": "^7.9.2",
    "babel-plugin-dynamic-import-node": "2.3.0",
    "babel-plugin-transform-react-remove-prop-types": "0.4.24"
  },
  "gitHead": "5c79f597bbd4e9f11801fbb36ef6570c74331b7b"
}
```

I get the following though with `npm ls babel-preset-razzle`

```
├── babel-preset-razzle@3.3.11  extraneous
└─┬ razzle@3.3.12
  └── UNMET DEPENDENCY babel-preset-razzle@latest

npm ERR! extraneous: babel-preset-razzle@3.3.11 ~/node_modules/babel-preset-razzle
npm ERR! missing: babel-preset-razzle@latest, required by razzle@3.3.12

```

**Comment by fivethreeo** [comment]
This is all better documented in canary. 4.0 coming soon.

**Comment by nnnoel** [comment]
Thanks. Pinning the exact version in resolutions worked for me.

```json
  "resolutions": {
    "babel-preset-razzle": "^3.3.12"
  }
```

**Comment by nnnoel** [comment]
Looks like there's a new error with the bump:

```
~/node_modules/babel-preset-razzle/babel-plugins/commonjs.js:4
  const commonjs = commonjsPlugin.default(api, options, dirname);
                                          ^
Error: Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):
ReferenceError: [BABEL] ~/server/app.js: api is not defined (While processing: "programmatic item")
```

Here's the full trace.
```
~/node_modules/babel-preset-razzle/babel-plugins/commonjs.js:4
  const commonjs = commonjsPlugin.default(api, options, dirname);
                                          ^
Error: Module build failed (from ./node_modules/razzle/config/babel-loader/razzle-babel-loader.js):
ReferenceError: [BABEL] ~/server/app.js: api is not defined (While processing: "programmatic item")
    at module.exports (~/node_modules/babel-preset-razzle/babel-plugins/commonjs.js:4:43)
    at ~/node_modules/razzle/node_modules/@babel/core/lib/config/full.js:199:14
    at Generator.next (<anonymous>)
    at Function.<anonymous> (~/node_modules/razzle/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (~/node_modules/gensync/index.js:261:32)
    at evaluateAsync (~/node_modules/gensync/index.js:291:5)
    at Function.errback (~/node_modules/gensync/index.js:113:7)
    at errback (~/node_modules/razzle/node_modules/@babel/core/lib/gensync-utils/async.js:70:18)
    at async (~/node_modules/gensync/index.js:188:31)
    at onFirstPause (~/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at cachedFunction (~/node_modules/razzle/node_modules/@babel/core/lib/config/caching.js:68:46)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor (~/node_modules/razzle/node_modules/@babel/core/lib/config/full.js:235:42)
    at loadPluginDescriptor.next (<anonymous>)
    at recurseDescriptors (~/node_modules/razzle/node_modules/@babel/core/lib/config/full.js:88:33)
    at recurseDescriptors.next (<anonymous>)
    at loadFullConfig (~/node_modules/razzle/node_modules/@babel/core/lib/config/full.js:142:6)
    at loadFullConfig.next (<anonymous>)
    at Function.transform (~/node_modules/razzle/node_modules/@babel/core/lib/transform.js:25:45)
    at transform.next (<anonymous>)
    at Object../server/app.js (~/public/assets/chunks/server.js:51141:7)
    at __webpack_require__ (~/public/assets/chunks/server.js:755:30)
    at fn (~/public/assets/chunks/server.js:60:20)
    at Object../server/index.js (~/public/assets/chunks/server.js:51151:11)
    at __webpack_require__ (~/public/assets/chunks/server.js:755:30)
    at fn (~/public/assets/chunks/server.js:60:20)
    at Object.0 (~/public/assets/chunks/server.js:51237:1)
    at __webpack_require__ (~/public/assets/chunks/server.js:755:30)
    at ~/public/assets/chunks/server.js:849:37
    at Object.<anonymous> (~/public/assets/chunks/server.js:852:10)
```

**Comment by fivethreeo** [comment]
I see what it is, will fix tomorrow.

**Comment by fivethreeo** [comment]
Fixed in v3.3.13
